# Generated by Django 4.1.5 on 2023-02-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VideoLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_file', models.FileField(max_length=255, upload_to='video_lessons/')),
                ('image', models.ImageField(max_length=255, upload_to='lesson_images/,')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lessons', to='video_lessons.lessonseries')),
            ],
        ),
    ]
