# Generated by Django 4.1.5 on 2023-02-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoLessons',
            new_name='VideoLesson',
        ),
    ]
