# Generated by Django 4.1.5 on 2023-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0002_rename_videolessons_videolesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='ordinal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
