# Generated by Django 4.1.5 on 2023-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0003_videolesson_ordinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonseries',
            name='description',
            field=models.TextField(default='description...', max_length=1024),
        ),
    ]
