# Generated by Django 4.1.5 on 2023-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0009_subscription_stripe_lookup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearningprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userlearningprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userlearningprofile',
            name='subscription_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
