# Generated by Django 4.1.5 on 2023-02-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0010_userlearningprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearningprofile',
            name='email',
            field=models.EmailField(default='none@none.com', max_length=254),
            preserve_default=False,
        ),
    ]
