# Generated by Django 4.1.5 on 2023-02-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0011_userlearningprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlearningprofile',
            name='email',
        ),
    ]
