# Generated by Django 4.1.5 on 2023-02-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lessons', '0012_remove_userlearningprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='lesson_images/,'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='video_lessons/'),
        ),
    ]
