# Generated by Django 3.2.16 on 2023-01-29 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('friendly_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('audio_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('audio_clip', models.FileField(blank=True, null=True, upload_to='product_audio_clips')),
                ('stock_level', models.IntegerField(default=20)),
                ('reorder_threshold', models.IntegerField(default=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('product_owner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduced_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('associated_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_products', to='products.product')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_product', to='products.product')),
            ],
        ),
    ]
