# Generated by Django 3.2.16 on 2023-01-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='audio_clip',
            field=models.FileField(blank=True, null=True, upload_to='product_audio_clips'),
        ),
    ]
