# Generated by Django 4.1.5 on 2023-02-12 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_stock_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_threshold',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
