# Generated by Django 3.2.16 on 2023-01-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230112_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='end_date',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='required_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_products', to='products.product'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product'),
        ),
    ]
