# Generated by Django 3.2.16 on 2023-01-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230124_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='required_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_products', to='products.product'),
        ),
    ]
