# Generated by Django 3.2.16 on 2023-01-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_specialoffer_required_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='duration',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
