# Generated by Django 3.2.16 on 2023-01-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230124_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='required_product',
        ),
    ]
