# Generated by Django 4.1.5 on 2023-02-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productassociation_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/tempfile.png', null=True, upload_to='product_images/'),
        ),
    ]
