# Generated by Django 3.2.16 on 2023-01-24 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_specialoffer_required_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='required_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_products', to='products.product'),
        ),
    ]
