# Generated by Django 4.1.5 on 2023-03-26 17:39

import datetime
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_specialoffer_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='end_date',
            field=models.DateField(default=products.models.SpecialOffer.return_default_end_date),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
